# Rewritten by scripts/switch-traffic.sh

# ACTIVE_COLOR=__ACTIVE_COLOR__

upstream orders_active {
    server __ACTIVE_CONTAINER__:3000;
}

server {
    listen 8080;

    location /router-status {
        default_type text/plain;
        return 200 "active-color: __ACTIVE_COLOR__\n";
    }

    location / {
        proxy_pass http://orders_active;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout 2s;
        proxy_read_timeout 5s;
    }
}